/// fail: Cannot return from void function

def foo() {
    return 5
}
